"""Service management schemas package."""

from .appointment_additional_info import (
    AppointmentAdditionalInfo,
    AppointmentAdditionalInfoFilters,
    AppointmentAdditionalInfoQueryOptions,
    AppointmentAdditionalInfoSorting,
    CreateAppointmentAdditionalInfo,
    UpdateAppointmentAdditionalInfo,
)
from .appointment_field_config import (
    AppointmentFieldConfig,
    AppointmentFieldConfigFilters,
    AppointmentFieldConfigQueryOptions,
    AppointmentFieldConfigSorting,
    CreateAppointmentFieldConfig,
    UpdateAppointmentFieldConfig,
)
from .service_appointment import (
    CreateServiceAppointment,
    ServiceAppointment,
    ServiceAppointmentFilters,
    ServiceAppointmentQueryOptions,
    ServiceAppointmentSorting,
    UpdateServiceAppointment,
)
from .service_person import (
    CreateServicePerson,
    ServicePerson,
    ServicePersonFilters,
    ServicePersonQueryOptions,
    ServicePersonSorting,
    UpdateServicePerson,
)
from .service_pricing_rule import (
    CreateServicePricingRule,
    ServicePricingRule,
    ServicePricingRuleCondition,
    ServicePricingRuleFilters,
    ServicePricingRuleQueryOptions,
    ServicePricingRuleSorting,
    UpdateServicePricingRule,
)
from .service_provider import (
    CreateServiceProvider,
    ServiceProvider,
    ServiceProviderFilters,
    ServiceProviderQueryOptions,
    ServiceProviderSorting,
    UpdateServiceProvider,
)
from .service_slot_query import (
    ServiceCandidateSlot,
    ServiceSlotQueryRequest,
    ServiceSlotQueryResponse,
)
from .service_time_off import (
    CreateServiceTimeOff,
    ServiceProviderTimeOffRecurrence,
    ServiceTimeOff,
    ServiceTimeOffFilters,
    ServiceTimeOffQueryOptions,
    ServiceTimeOffSorting,
    UpdateServiceTimeOff,
)

__all__ = [
    "AppointmentAdditionalInfo",
    "CreateAppointmentAdditionalInfo",
    "UpdateAppointmentAdditionalInfo",
    "AppointmentAdditionalInfoFilters",
    "AppointmentAdditionalInfoSorting",
    "AppointmentAdditionalInfoQueryOptions",
    "AppointmentFieldConfig",
    "CreateAppointmentFieldConfig",
    "UpdateAppointmentFieldConfig",
    "AppointmentFieldConfigFilters",
    "AppointmentFieldConfigSorting",
    "AppointmentFieldConfigQueryOptions",
    "ServiceAppointment",
    "CreateServiceAppointment",
    "UpdateServiceAppointment",
    "ServiceAppointmentFilters",
    "ServiceAppointmentSorting",
    "ServiceAppointmentQueryOptions",
    "ServicePerson",
    "CreateServicePerson",
    "UpdateServicePerson",
    "ServicePersonFilters",
    "ServicePersonSorting",
    "ServicePersonQueryOptions",
    "ServicePricingRuleCondition",
    "ServicePricingRule",
    "CreateServicePricingRule",
    "UpdateServicePricingRule",
    "ServicePricingRuleFilters",
    "ServicePricingRuleSorting",
    "ServicePricingRuleQueryOptions",
    "ServiceProvider",
    "CreateServiceProvider",
    "UpdateServiceProvider",
    "ServiceProviderFilters",
    "ServiceProviderSorting",
    "ServiceProviderQueryOptions",
    "ServiceTimeOff",
    "CreateServiceTimeOff",
    "UpdateServiceTimeOff",
    "ServiceProviderTimeOffRecurrence",
    "ServiceTimeOffFilters",
    "ServiceTimeOffSorting",
    "ServiceTimeOffQueryOptions",
    "ServiceSlotQueryRequest",
    "ServiceCandidateSlot",
    "ServiceSlotQueryResponse",
]
