"""Conversation message schema definitions for chat and email messages.

Message schemas define the structure of individual messages exchanged in conversations between users
and AI agents. Supports multiple message types (chat, email) with distinct schemas for user-originated
and agent-originated messages, enabling proper message threading, context tracking, and channel-specific
formatting.
"""

from typing import Literal, Optional, Union

from pydantic import BaseModel as PydanticBaseModel
from pydantic import ConfigDict, Field

from wiil.types.conversation_types import MessageType


class BaseChatMessage(PydanticBaseModel):
    """Base chat message schema.

    Foundation schema for all chat-based messages containing core fields shared by both user and
    assistant messages. Extended by UserChatMessage and AssistantChatMessage with role-specific
    identifiers for message threading and conversation flow tracking.

    Architecture Context:
        - Extended By: UserChatMessage, AssistantChatMessage for role-specific messages
        - Relationship: N:1 - Multiple messages belong to one conversation (via conversation_config_id)
        - Storage: Stored in conversation message arrays and separate message collections
        - LLM Context: llm_conversation_id enables multi-turn context tracking with LLM providers

    Message Flow:
        - User sends message → UserChatMessage created → Agent processes → AssistantChatMessage generated
        - Messages linked via user_message_id and assistant_message_id for threading
    """

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        use_enum_values=True,
    )

    conversation_config_id: str = Field(
        ...,
        description="ID of the conversation configuration this message belongs to (N:1 relationship, references ServiceConversationConfig for conversation context and metadata)"
    )
    message: str = Field(
        ...,
        description="Text content of the message sent by user or generated by agent, may include plain text or markdown formatting depending on channel capabilities"
    )
    timestamp: int = Field(
        ...,
        description="Unix timestamp in milliseconds when the message was created and sent (default: current time, used for chronological ordering and latency analysis)"
    )
    llm_conversation_id: Optional[str] = Field(
        None,
        description="LLM provider conversation thread ID for multi-turn context tracking (OpenAI thread ID, Anthropic conversation ID) enabling context retention across messages"
    )


class BaseEmailMessage(BaseChatMessage):
    """Base email message schema extending chat message with email-specific fields.

    Extends BaseChatMessage with email-specific attributes including subject line and email
    identifier flag. Used as foundation for user and assistant email messages in email-based
    conversation channels.

    Architecture Context:
        - Extends: BaseChatMessage with email-specific fields
        - Extended By: UserEmailMessage, AssistantEmailMessage
        - Channel: Used exclusively for EMAIL conversation type
        - Threading: Subject line enables email thread grouping and conversation continuity

    Email Features:
        - Subject line for email clients and threading
        - is_email flag distinguishes email messages from chat messages in unified message stores
    """

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        use_enum_values=True,
    )

    subject: str = Field(
        ...,
        description="Subject line of the email message used in email clients and for email thread grouping, typically maintained across conversation for proper threading"
    )
    is_email: Literal[True] = Field(
        True,
        description="Flag indicating this is an email message (always true), distinguishes email messages from chat messages in unified message collections",
        alias="isEmail"
    )


class UserChatMessage(BaseChatMessage):
    """User chat message schema.

    Represents a message sent by a user/customer in a chat conversation. Contains user-specific
    identifiers for message threading and links to the previous assistant message to maintain
    conversation context and flow.

    Architecture Context:
        - Extends: BaseChatMessage with user-specific fields
        - Message Type: Always 'user' (MessageType.USER)
        - Threading: Links to previous assistant message via last_assistant_message_id
        - Flow: User message → Agent processes → AssistantChatMessage generated

    Message Threading:
        - user_message_id: Unique identifier for this user message
        - last_assistant_message_id: References the assistant's previous message being responded to
        - Enables tracking conversation turns and maintaining context
    """

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        use_enum_values=True,
    )

    message_type: Literal[MessageType.USER] = Field(
        MessageType.USER,
        description="Message type identifier fixed to 'user' indicating this message was sent by the customer/end-user"
    )
    user_message_id: Optional[str] = Field(
        None,
        description="Unique identifier for this user message (typically UUID) used for message threading, deduplication, and reference in assistant responses"
    )
    last_assistant_message_id: Optional[str] = Field(
        None,
        description="ID of the last assistant message this user message is responding to, creates bidirectional message threading for conversation flow tracking"
    )


class AssistantChatMessage(BaseChatMessage):
    """Assistant chat message schema.

    Represents a message generated by the AI agent in a chat conversation. Contains agent-specific
    identifiers and links to the user message being responded to, enabling proper conversation
    threading and context tracking.

    Architecture Context:
        - Extends: BaseChatMessage with assistant-specific fields
        - Message Type: Always 'assistant' (MessageType.AGENT)
        - Threading: Links to user message being responded to via last_user_message_id
        - Flow: User message received → Agent generates → AssistantChatMessage created

    Message Threading:
        - assistant_message_id: Required unique identifier for this assistant message
        - last_user_message_id: References the user message being responded to
        - Enables conversation turn tracking and response latency measurement
    """

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        use_enum_values=True,
    )

    message_type: Literal[MessageType.AGENT] = Field(
        MessageType.AGENT,
        description="Message type identifier fixed to 'assistant' indicating this message was generated by the AI agent"
    )
    assistant_message_id: str = Field(
        ...,
        description="Required unique identifier for this assistant message (typically UUID) used for message threading, user response linking, and performance tracking"
    )
    last_user_message_id: Optional[str] = Field(
        None,
        description="ID of the user message this assistant message is responding to, creates bidirectional message threading and enables response latency measurement"
    )


class UserEmailMessage(BaseEmailMessage):
    """User email message schema.

    Represents an email message sent by a user/customer. Extends base email schema with user-specific
    fields and optional provider message ID for integration with external email services (Gmail, Outlook, etc.).

    Architecture Context:
        - Extends: BaseEmailMessage with user-specific fields
        - Message Type: Always 'user' (MessageType.USER)
        - Channel: Used exclusively for EMAIL conversation type
        - Provider Integration: Links to external email service message IDs

    Email Integration:
        - provider_message_id enables tracking emails across platforms
        - Supports Gmail API, Outlook Graph API, SendGrid, etc.
        - Used for reply-to threading and email service synchronization
    """

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        use_enum_values=True,
    )

    message_type: Literal[MessageType.USER] = Field(
        MessageType.USER,
        description="Message type identifier fixed to 'user' indicating this email was sent by the customer/end-user"
    )
    provider_message_id: Optional[str] = Field(
        None,
        description="Provider-specific email message ID from external email services (Gmail message ID, Outlook message ID, SendGrid message ID) for email tracking and reply threading"
    )


class AssistantEmailMessage(BaseEmailMessage):
    """Assistant email message schema.

    Represents an email message generated by the AI agent in response to a user email. Extends base
    email schema with assistant message type, used for automated email responses and email-based
    customer support interactions.

    Architecture Context:
        - Extends: BaseEmailMessage with assistant-specific fields
        - Message Type: Always 'assistant' (MessageType.AGENT)
        - Channel: Used exclusively for EMAIL conversation type
        - Use Cases: Automated customer support replies, FAQ responses, ticket acknowledgments

    Email Response Features:
        - Inherits subject line from BaseEmailMessage for thread continuity
        - Agent-generated content formatted for email clients
        - Supports HTML formatting and attachments via message content
    """

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        use_enum_values=True,
    )

    message_type: Literal[MessageType.AGENT] = Field(
        MessageType.AGENT,
        description="Message type identifier fixed to 'assistant' indicating this email was generated by the AI agent"
    )


# Union type for all conversation messages
ConversationMessage = Union[UserChatMessage, AssistantChatMessage, UserEmailMessage, AssistantEmailMessage]
ChatMessage = Union[UserChatMessage, AssistantChatMessage, UserEmailMessage, AssistantEmailMessage]
