"""Pydantic models for WIIL Platform entities.

This module provides comprehensive Pydantic models mirroring
the TypeScript schemas
in src/core/. All models follow Pythonic conventions with camelCase aliases for
JSON serialization compatibility.
"""

# Base models
from wiil.models.base import Address, BaseModel, EntityModel, LanguageCode

# Account models
from wiil.models.account import (
    CreateProject,
    Organization,
    OrganizationServiceStatusRecord,
    Project,
    UpdateProject,
    SUPPORTED_BUSINESS_VERTICALS,
    SupportedBusinessVerticalId,
)

# Assistant setup models
from wiil.models.assistant_setups import (
    AssistantSetupResult,
    AdvanceBaseAssistant,
    BaseAssistant,
    ChainedPhoneAssistantSetup,
    ChainedWebAssistantSetup,
    PhoneAssistantSetup,
    WebAssistantSetup,
)

# Business management models
from wiil.models.business_mgt import (
    # Appointment additional info
    AppointmentAdditionalInfo,
    AppointmentAdditionalInfoFilters,
    AppointmentAdditionalInfoQueryOptions,
    AppointmentAdditionalInfoSorting,
    CreateAppointmentAdditionalInfo,
    UpdateAppointmentAdditionalInfo,
    # Appointment field config
    AppointmentFieldConfig,
    AppointmentFieldConfigFilters,
    AppointmentFieldConfigQueryOptions,
    AppointmentFieldConfigSorting,
    CreateAppointmentFieldConfig,
    UpdateAppointmentFieldConfig,
    # Customer
    Customer,
    CustomerFilters,
    CustomerGroup,
    CustomerQueryOptions,
    CustomerSorting,
    CreateCustomer,
    CreateCustomerGroup,
    CreateDisplayOrderPlacement,
    UpdateCustomer,
    UpdateCustomerGroup,
    CategoryDisplayOrderRequest,
    CategoryDisplayOrderResponse,
    CategoryDisplayOrdersRequest,
    CategoryItemDisplayOrdersRequest,
    CategoryItemOrderEntry,
    CategoryOrderEntry,
    DisplayOrderPositionIntent,
    DisplayOrderPositionMode,
    DisplayOrderRequest,
    DisplayOrderResponse,
    # Menu configuration
    MenuCategory,
    CreateMenuCategory,
    UpdateMenuCategory,
    BusinessMenuItem,
    CreateBusinessMenuItem,
    UpdateBusinessMenuItem,
    NutritionalInfo,
    # Menu order
    MenuOrder,
    MenuOrderItem,
    MenuOrderItemBase,
    MenuItemCustomization,
    DeliveryAddress,
    CreateMenuOrder,
    UpdateMenuOrder,
    UpdateMenuOrderStatus,
    # Order shared
    AppliedDiscount,
    AppliedPricingRule,
    AppliedTax,
    DEFAULT_MENU_ITEM_DAYPARTS,
    MenuItemDaypart,
    OrderAddress,
    OrderCustomer,
    OrderPricing,
    # Discount and pricing shared
    CreateDiscountRule,
    DiscountRule,
    DiscountRuleFilters,
    DiscountRuleQueryOptions,
    DiscountRuleSorting,
    CreateTaxRule,
    TaxRule,
    TaxRuleFilters,
    TaxRuleQueryOptions,
    TaxRuleSorting,
    BusinessLocation,
    BusinessLocationFilters,
    BusinessLocationQueryOptions,
    BusinessLocationSorting,
    BusinessLocationStatus,
    CreateBusinessLocation,
    GeoCoordinates,
    UpdateBusinessLocation,
    PricingRuleAction,
    UpdateTaxRule,
    UpdateDiscountRule,
    # Booking shared
    ReservationType,
    ServiceBookingRules,
    ServiceDepositStrategy,
    # Product configuration
    ProductCategory,
    CreateProductCategory,
    UpdateProductCategory,
    BusinessProduct,
    CreateBusinessProduct,
    UpdateBusinessProduct,
    ProductDimensions,
    # Product order
    ProductOrder,
    ProductOrderItem,
    ProductOrderItemBase,
    CreateProductOrder,
    UpdateProductOrder,
    UpdateProductOrderStatus,
    InventoryAdjustment,
    OrderInventoryUpdate,
    # Reservation
    ReservationSettings,
    CreateReservationSettings,
    UpdateReservationSettings,
    Reservation,
    CreateReservation,
    UpdateReservation,
    # Reservation resource
    Resource,
    CreateResource,
    CreateResourceInstanceInput,
    UpdateResource,
    RoomResource,
    RentalResource,
    # Floor plan definition
    FloorPlanDefinition,
    CreateFloorPlanDefinition,
    CreateFloorPlanSectionInput,
    CreateFloorPlanTablePlacementInput,
    # Service appointment
    ServiceAppointment,
    ServiceAppointmentFilters,
    ServiceAppointmentQueryOptions,
    ServiceAppointmentSorting,
    CreateServiceAppointment,
    CreateServicePricingRule,
    CreateServiceProvider,
    CreateServiceTimeOff,
    UpdateServiceAppointment,
    UpdateServicePricingRule,
    UpdateServiceProvider,
    UpdateServiceTimeOff,
    # Service configuration
    BusinessServiceConfig,
    CreateBusinessService,
    UpdateBusinessService,
    # Service person
    ServicePerson,
    ServicePersonFilters,
    ServicePersonQueryOptions,
    ServicePersonSorting,
    ServicePricingRule,
    ServicePricingRuleCondition,
    ServicePricingRuleFilters,
    ServicePricingRuleQueryOptions,
    ServicePricingRuleSorting,
    ServiceProvider,
    ServiceProviderFilters,
    ServiceProviderQueryOptions,
    ServiceProviderSorting,
    ServiceCandidateSlot,
    ServiceSlotQueryRequest,
    ServiceSlotQueryResponse,
    ServiceTimeOff,
    ServiceProviderTimeOffRecurrence,
    ServiceTimeOffFilters,
    ServiceTimeOffQueryOptions,
    ServiceTimeOffSorting,
    CreateServicePerson,
    UpdateServicePerson,
    ShippingAddress,
    ShippingAddressFilters,
    ShippingAddressSorting,
    ShippingAddressQueryOptions,
    # Property configuration
    Property,
    ResidentialDetails,
    CommercialDetails,
    LandDetails,
    CreateProperty,
    UpdateProperty,
    PropertyCategory,
    CreatePropertyCategory,
    UpdatePropertyCategory,
    PropertyAddress,
    CreatePropertyAddress,
    UpdatePropertyAddress,
    PropertyFeatures,
    PropertyCatalog,
    BusinessPropertyCatalog,
    Coordinates,
    # Property inquiry
    PropertyInquiry,
    CreatePropertyInquiry,
    UpdatePropertyInquiry,
    UpdatePropertyInquiryStatus,
    PropertyInquiryFilters,
    PropertyInquirySorting,
    PropertyInquiryQueryOptions,
)

# Conversation models
from wiil.models.conversation import (
    # Conversation configuration
    BaseConversationConfig,
    CallTransfer,
    ConversationFilters,
    ConversationQueryOptions,
    ConversationSorting,
    ConversationStateHistory,
    ConversationSummary,
    DateRange,
    Message,
    ServiceConversationConfig,
    # Conversation messages
    AssistantChatMessage,
    AssistantEmailMessage,
    BaseChatMessage,
    BaseEmailMessage,
    ChatMessage,
    ConversationMessage,
    UserChatMessage,
    UserEmailMessage,
    BusinessCallRequest,
    CallingHours,
    CreateCallRequest,
    CreateEmailRequest,
    EmailAttachment,
    EmailRecipient,
    EmailRequest,
    CreateSmsRequest,
    SmsRequest,
    # Translation session models
    TranslationSession,
    TranslationSessionStatus,
    TranslationSessionStateHistory,
    CreateTranslationSession,
    UpdateTranslationSession,
    TransitionTranslationSession,
    # Translation participant models
    TranslationParticipant,
    TranslationParticipantRole,
    CreateTranslationParticipant,
    UpdateTranslationParticipant,
    # Translation transcript models
    TranslationTranscriptEntry,
    CreateTranslationTranscriptEntry,
    # Translation request/response DTOs
    TranslationSessionRequest,
    TranslationSessionParticipantRequest,
    TranslationSessionInitiatorRequest,
    TranslationSessionAccess,
    TranslationParticipantAccess,
    TranslationDirection,
)

# Request models
from wiil.models.request import (
    AccountPaginatedTimestampQuery,
    BasePaginatedResult,
    PaginatedAccountRequest,
    PaginatedResultType,
    PaginationMeta,
    PaginationRequest,
    SearchablePaginationRequest,
    SortDirection,
    TimestampQuery,
)

# Service configuration models
from wiil.models.service_mgt import (
    # Agent configuration
    AgentConfiguration,
    AgentConfigurationDeleteRequest,
    CreateAgentConfiguration,
    UpdateAgentConfiguration,
    # Agent graph
    AgentDeploymentNode,
    AgentGraph,
    # Call transfer
    CallTransferConfig,
    TransferType,
    # Deployment configuration
    CreateChainDeploymentConfiguration,
    CreateDeploymentConfiguration,
    DeploymentConfiguration,
    DeploymentConfigurationDetails,
    DeploymentConfigurationResult,
    UpdateDeploymentConfiguration,
    # Instruction configuration
    CreateInstructionConfiguration,
    InstructionConfiguration,
    UpdateInstructionConfiguration,
    # Interaction channels
    CallChannel,
    ChannelConfiguration,
    ChannelSetupRequest,
    ChannelUpdateRequest,
    CreateDeploymentChannel,
    CreateMobileAppChannel,
    CreateWebChannel,
    DeploymentChannel,
    DeploymentChannelDeletionRequest,
    DeploymentChannelInfo,
    DeploymentChannelRequest,
    DeploymentChannelWithDeployment,
    MobileAppChannel,
    MobileAppChannelConfig,
    PhoneChannelConfig,
    SmsChannel,
    UpdateDeploymentChannel,
    WebChannel,
    WebChannelConfig,
    # Knowledge
    CreateTextKnowledgeSource,
    KnowledgeSource,
    # Phone configuration
    PhoneConfiguration,
    UpdatePhoneConfiguration,
    # Phone number
    BasePhoneNumberInfo,
    BusinessPhoneNumberPurchaseRequest,
    CreatePhoneNumberPurchase,
    PhoneCapabilities,
    PhoneNumberPrice,
    PhoneNumberPricing,
    PhoneNumberPurchase,
    PhoneProviderResponse,
    # Provisioning
    ChainConfiguration,
    CreateChainConfiguration,
    CreateProvisioningConfig,
    CreateTranslationChainConfig,
    ProvisioningConfigChain,
    SttModelConfig,
    TranslationChainConfig,
    TtsModelConfig,
    UpdateChainConfiguration,
    UpdateProvisioningConfig,
    UpdateTranslationChainConfig,
    # Support LLM
    WiilSupportModel,
    # Voice and language
    Language,
    SupportedLanguages,
    SupportedVoices,
    Voice,
    VoiceGender,
    # Dynamic setup
    DynamicAgentProcessingState,
    DynamicAgentSetupResult,
    DynamicBaseAgentSetup,
    DynamicModelConfiguration,
    DynamicPhoneAgentSetup,
    DynamicPhoneAgentSetupResult,
    DynamicSTTModelConfiguration,
    DynamicTTSModelConfiguration,
    DynamicWebAgentSetup,
    DynamicWebAgentSetupResult,
    ProcessingStatus,
    UpdateDynamicPhoneAgent,
    UpdateDynamicWebAgent,
)

# Re-export types for convenience
from wiil.types import (
    # Account types
    BusinessSupportServices,
    ServiceStatus,
    ServiceSuspensionType,
    # Business types
    AppointmentStatus,
    BestTimeToCall,
    BusinessDocumentTypes,
    BusinessServiceDocumentTypes,
    BusinessServiceType,
    CalendarProvider,
    CallPriority,
    ExternalRef,
    InventoryUnit,
    MenuOrderType,
    OrderStatus,
    PaymentStatus,
    PreferredContactMethod,
    ProductOrderType,
    RecurrenceType,
    ReservationSettingType,
    ReservationSlotStatus,
    ResourceReservationDurationUnit,
    ResourceType,
    RestockStatus,
    StockAdjustmentType,
    StockStatus,
    # Service configuration types
    AssistantType,
    DeploymentProvisioningType,
    DeploymentStatus,
    DeploymentType,
    LLMRequestType,
    LLMType,
    MobilePlatform,
    ModelProprietor,
    OttCommunicationType,
    PhoneNumberType,
    PhonePurchaseStatus,
    PhoneStatus,
    ProviderType,
    SupportedLLMKit,
    SupportedProprietor,
    # Conversation types
    ConversationDirection,
    ConversationEventType,
    ConversationStatus,
    ConversationSummarySentiment,
    MessageType,
    ServiceConversationType,
    TranslationDirection,
    # Knowledge types
    KnowledgeBaseProcessingStatus,
    KnowledgeTypes,
    StorageTier,
    SupportedDocumentTypes,
)

__all__ = [
    # Base models
    "Address",
    "BaseModel",
    "EntityModel",
    "LanguageCode",
    # Account models
    "CreateProject",
    "Organization",
    "OrganizationServiceStatusRecord",
    "Project",
    "UpdateProject",
    "SUPPORTED_BUSINESS_VERTICALS",
    "SupportedBusinessVerticalId",
    # Assistant setup models
    "AssistantSetupResult",
    "AdvanceBaseAssistant",
    "BaseAssistant",
    "ChainedPhoneAssistantSetup",
    "ChainedWebAssistantSetup",
    "PhoneAssistantSetup",
    "WebAssistantSetup",
    # Business management models
    "AppointmentAdditionalInfo",
    "AppointmentAdditionalInfoFilters",
    "AppointmentAdditionalInfoQueryOptions",
    "AppointmentAdditionalInfoSorting",
    "CreateAppointmentAdditionalInfo",
    "UpdateAppointmentAdditionalInfo",
    "AppointmentFieldConfig",
    "AppointmentFieldConfigFilters",
    "AppointmentFieldConfigQueryOptions",
    "AppointmentFieldConfigSorting",
    "CreateAppointmentFieldConfig",
    "UpdateAppointmentFieldConfig",
    "Customer",
    "CustomerFilters",
    "CustomerGroup",
    "CustomerQueryOptions",
    "CustomerSorting",
    "CreateCustomer",
    "CreateCustomerGroup",
    "CreateDisplayOrderPlacement",
    "UpdateCustomer",
    "UpdateCustomerGroup",
    "CategoryDisplayOrderRequest",
    "CategoryDisplayOrderResponse",
    "CategoryDisplayOrdersRequest",
    "CategoryItemDisplayOrdersRequest",
    "CategoryItemOrderEntry",
    "CategoryOrderEntry",
    "DisplayOrderPositionIntent",
    "DisplayOrderPositionMode",
    "DisplayOrderRequest",
    "DisplayOrderResponse",
    "MenuCategory",
    "CreateMenuCategory",
    "UpdateMenuCategory",
    "BusinessMenuItem",
    "CreateBusinessMenuItem",
    "UpdateBusinessMenuItem",
    "NutritionalInfo",
    "MenuOrder",
    "MenuOrderItem",
    "MenuOrderItemBase",
    "MenuItemCustomization",
    "DeliveryAddress",
    "CreateMenuOrder",
    "UpdateMenuOrder",
    "UpdateMenuOrderStatus",
    "OrderAddress",
    "OrderCustomer",
    "OrderPricing",
    "AppliedDiscount",
    "AppliedPricingRule",
    "AppliedTax",
    "MenuItemDaypart",
    "DEFAULT_MENU_ITEM_DAYPARTS",
    "DiscountRule",
    "CreateDiscountRule",
    "UpdateDiscountRule",
    "DiscountRuleFilters",
    "DiscountRuleSorting",
    "DiscountRuleQueryOptions",
    "TaxRule",
    "CreateTaxRule",
    "UpdateTaxRule",
    "TaxRuleFilters",
    "TaxRuleSorting",
    "TaxRuleQueryOptions",
    "BusinessLocationStatus",
    "GeoCoordinates",
    "BusinessLocation",
    "CreateBusinessLocation",
    "UpdateBusinessLocation",
    "BusinessLocationFilters",
    "BusinessLocationSorting",
    "BusinessLocationQueryOptions",
    "PricingRuleAction",
    "ServiceDepositStrategy",
    "ReservationType",
    "ServiceBookingRules",
    "ProductCategory",
    "CreateProductCategory",
    "UpdateProductCategory",
    "BusinessProduct",
    "CreateBusinessProduct",
    "UpdateBusinessProduct",
    "ProductDimensions",
    "ProductOrder",
    "ProductOrderItem",
    "ProductOrderItemBase",
    "CreateProductOrder",
    "UpdateProductOrder",
    "UpdateProductOrderStatus",
    "InventoryAdjustment",
    "OrderInventoryUpdate",
    "ReservationSettings",
    "CreateReservationSettings",
    "UpdateReservationSettings",
    "Reservation",
    "CreateReservation",
    "UpdateReservation",
    "Resource",
    "CreateResource",
    "CreateResourceInstanceInput",
    "UpdateResource",
    "RoomResource",
    "RentalResource",
    "FloorPlanDefinition",
    "CreateFloorPlanDefinition",
    "CreateFloorPlanSectionInput",
    "CreateFloorPlanTablePlacementInput",
    "ServiceAppointment",
    "ServiceAppointmentFilters",
    "ServiceAppointmentQueryOptions",
    "ServiceAppointmentSorting",
    "CreateServiceAppointment",
    "CreateServicePricingRule",
    "CreateServiceProvider",
    "CreateServiceTimeOff",
    "UpdateServiceAppointment",
    "UpdateServicePricingRule",
    "UpdateServiceProvider",
    "UpdateServiceTimeOff",
    "BusinessServiceConfig",
    "CreateBusinessService",
    "UpdateBusinessService",
    "ServicePerson",
    "ServicePersonFilters",
    "ServicePersonQueryOptions",
    "ServicePersonSorting",
    "ServicePricingRule",
    "ServicePricingRuleCondition",
    "ServicePricingRuleFilters",
    "ServicePricingRuleQueryOptions",
    "ServicePricingRuleSorting",
    "ServiceProvider",
    "ServiceProviderFilters",
    "ServiceProviderQueryOptions",
    "ServiceProviderSorting",
    "ServiceCandidateSlot",
    "ServiceSlotQueryRequest",
    "ServiceSlotQueryResponse",
    "ServiceTimeOff",
    "ServiceProviderTimeOffRecurrence",
    "ServiceTimeOffFilters",
    "ServiceTimeOffQueryOptions",
    "ServiceTimeOffSorting",
    "CreateServicePerson",
    "UpdateServicePerson",
    "ShippingAddress",
    "ShippingAddressFilters",
    "ShippingAddressSorting",
    "ShippingAddressQueryOptions",
    "Property",
    "ResidentialDetails",
    "CommercialDetails",
    "LandDetails",
    "CreateProperty",
    "UpdateProperty",
    "PropertyCategory",
    "CreatePropertyCategory",
    "UpdatePropertyCategory",
    "PropertyAddress",
    "CreatePropertyAddress",
    "UpdatePropertyAddress",
    "PropertyFeatures",
    "PropertyCatalog",
    "BusinessPropertyCatalog",
    "Coordinates",
    "PropertyInquiry",
    "CreatePropertyInquiry",
    "UpdatePropertyInquiry",
    "UpdatePropertyInquiryStatus",
    "PropertyInquiryFilters",
    "PropertyInquirySorting",
    "PropertyInquiryQueryOptions",
    # Conversation models
    "BaseConversationConfig",
    "CallTransfer",
    "ConversationFilters",
    "ConversationQueryOptions",
    "ConversationSorting",
    "ConversationStateHistory",
    "ConversationSummary",
    "DateRange",
    "Message",
    "ServiceConversationConfig",
    "AssistantChatMessage",
    "AssistantEmailMessage",
    "BaseChatMessage",
    "BaseEmailMessage",
    "ChatMessage",
    "ConversationMessage",
    "UserChatMessage",
    "UserEmailMessage",
    "BusinessCallRequest",
    "CallingHours",
    "CreateCallRequest",
    "CreateEmailRequest",
    "EmailAttachment",
    "EmailRecipient",
    "EmailRequest",
    "CreateSmsRequest",
    "SmsRequest",
    # Translation session models
    "TranslationSession",
    "TranslationSessionStatus",
    "TranslationSessionStateHistory",
    "CreateTranslationSession",
    "UpdateTranslationSession",
    "TransitionTranslationSession",
    # Translation participant models
    "TranslationParticipant",
    "TranslationParticipantRole",
    "CreateTranslationParticipant",
    "UpdateTranslationParticipant",
    # Translation transcript models
    "TranslationTranscriptEntry",
    "CreateTranslationTranscriptEntry",
    # Translation request/response DTOs
    "TranslationSessionRequest",
    "TranslationSessionParticipantRequest",
    "TranslationSessionInitiatorRequest",
    "TranslationSessionAccess",
    "TranslationParticipantAccess",
    "TranslationDirection",
    # Request models
    "AccountPaginatedTimestampQuery",
    "BasePaginatedResult",
    "PaginatedAccountRequest",
    "PaginatedResultType",
    "PaginationMeta",
    "PaginationRequest",
    "SearchablePaginationRequest",
    "SortDirection",
    "TimestampQuery",
    # Service configuration models
    "AgentConfiguration",
    "AgentConfigurationDeleteRequest",
    "CreateAgentConfiguration",
    "UpdateAgentConfiguration",
    "AgentDeploymentNode",
    "AgentGraph",
    "CallTransferConfig",
    "TransferType",
    "CreateChainDeploymentConfiguration",
    "CreateDeploymentConfiguration",
    "DeploymentConfiguration",
    "DeploymentConfigurationDetails",
    "DeploymentConfigurationResult",
    "UpdateDeploymentConfiguration",
    "CreateInstructionConfiguration",
    "InstructionConfiguration",
    "UpdateInstructionConfiguration",
    "CallChannel",
    "ChannelConfiguration",
    "ChannelSetupRequest",
    "ChannelUpdateRequest",
    "CreateDeploymentChannel",
    "CreateMobileAppChannel",
    "CreateWebChannel",
    "DeploymentChannel",
    "DeploymentChannelDeletionRequest",
    "DeploymentChannelInfo",
    "DeploymentChannelRequest",
    "DeploymentChannelWithDeployment",
    "MobileAppChannel",
    "MobileAppChannelConfig",
    "PhoneChannelConfig",
    "SmsChannel",
    "UpdateDeploymentChannel",
    "WebChannel",
    "WebChannelConfig",
    "CreateTextKnowledgeSource",
    "KnowledgeSource",
    "PhoneConfiguration",
    "UpdatePhoneConfiguration",
    "BasePhoneNumberInfo",
    "BusinessPhoneNumberPurchaseRequest",
    "CreatePhoneNumberPurchase",
    "PhoneCapabilities",
    "PhoneNumberPrice",
    "PhoneNumberPricing",
    "PhoneNumberPurchase",
    "PhoneProviderResponse",
    "ChainConfiguration",
    "CreateChainConfiguration",
    "CreateProvisioningConfig",
    "CreateTranslationChainConfig",
    "ProvisioningConfigChain",
    "SttModelConfig",
    "TranslationChainConfig",
    "TtsModelConfig",
    "UpdateChainConfiguration",
    "UpdateProvisioningConfig",
    "UpdateTranslationChainConfig",
    "WiilSupportModel",
    "Language",
    "SupportedLanguages",
    "SupportedVoices",
    "Voice",
    "VoiceGender",
    "DynamicAgentProcessingState",
    "DynamicAgentSetupResult",
    "DynamicBaseAgentSetup",
    "DynamicModelConfiguration",
    "DynamicPhoneAgentSetup",
    "DynamicPhoneAgentSetupResult",
    "DynamicSTTModelConfiguration",
    "DynamicTTSModelConfiguration",
    "DynamicWebAgentSetup",
    "DynamicWebAgentSetupResult",
    "ProcessingStatus",
    "UpdateDynamicPhoneAgent",
    "UpdateDynamicWebAgent",
    # Account types
    "BusinessSupportServices",
    "ServiceStatus",
    "ServiceSuspensionType",
    # Business types
    "AppointmentStatus",
    "BestTimeToCall",
    "BusinessDocumentTypes",
    "BusinessServiceDocumentTypes",
    "BusinessServiceType",
    "CalendarProvider",
    "CallPriority",
    "ExternalRef",
    "InventoryUnit",
    "MenuOrderType",
    "OrderStatus",
    "PaymentStatus",
    "PreferredContactMethod",
    "ProductOrderType",
    "RecurrenceType",
    "ReservationSettingType",
    "ReservationSlotStatus",
    "ResourceReservationDurationUnit",
    "ResourceType",
    "RestockStatus",
    "StockAdjustmentType",
    "StockStatus",
    # Service configuration types
    "AssistantType",
    "DeploymentProvisioningType",
    "DeploymentStatus",
    "DeploymentType",
    "LLMRequestType",
    "LLMType",
    "MobilePlatform",
    "ModelProprietor",
    "OttCommunicationType",
    "PhoneNumberType",
    "PhonePurchaseStatus",
    "PhoneStatus",
    "ProviderType",
    "SupportedLLMKit",
    "SupportedProprietor",
    # Conversation types
    "ConversationDirection",
    "ConversationEventType",
    "ConversationStatus",
    "ConversationSummarySentiment",
    "MessageType",
    "ServiceConversationType",
    "TranslationDirection",
    # Knowledge types
    "KnowledgeBaseProcessingStatus",
    "KnowledgeTypes",
    "StorageTier",
    "SupportedDocumentTypes",
]
