"""Pydantic models for WIIL Platform entities.

This module provides comprehensive Pydantic models mirroring the TypeScript schemas
in src/core/. All models follow Pythonic conventions with camelCase aliases for
JSON serialization compatibility.
"""

# Base models
from wiil.models.base import Address, BaseModel, LanguageCode

# Account models
from wiil.models.account import (
    CreateProject,
    Organization,
    OrganizationServiceStatusRecord,
    Project,
    UpdateProject,
    SUPPORTED_BUSINESS_VERTICALS,
    SupportedBusinessVerticalId,
)

# Assistant setup models
from wiil.models.assistant_setups import (
    AssistantSetupResult,
    AdvanceBaseAssistant,
    BaseAssistant,
    ChainedPhoneAssistantSetup,
    ChainedWebAssistantSetup,
    PhoneAssistantSetup,
    WebAssistantSetup,
)

# Business management models
from wiil.models.business_mgt import (
    # Appointment additional info
    AppointmentAdditionalInfo,
    CreateAppointmentAdditionalInfo,
    UpdateAppointmentAdditionalInfo,
    # Appointment field config
    AppointmentFieldConfig,
    CreateAppointmentFieldConfig,
    UpdateAppointmentFieldConfig,
    # Customer
    Customer,
    CreateCustomer,
    UpdateCustomer,
    # Menu configuration
    MenuCategory,
    CreateMenuCategory,
    UpdateMenuCategory,
    BusinessMenuItem,
    CreateBusinessMenuItem,
    UpdateBusinessMenuItem,
    MenuQRCode,
    NutritionalInfo,
    # Menu order
    MenuOrder,
    MenuOrderItem,
    MenuOrderItemBase,
    MenuItemCustomization,
    DeliveryAddress,
    CreateMenuOrder,
    UpdateMenuOrder,
    UpdateMenuOrderStatus,
    # Order shared
    OrderAddress,
    OrderCustomer,
    OrderPricing,
    # Product configuration
    ProductCategory,
    CreateProductCategory,
    UpdateProductCategory,
    BusinessProduct,
    CreateBusinessProduct,
    UpdateBusinessProduct,
    ProductDimensions,
    # Product order
    ProductOrder,
    ProductOrderItem,
    ProductOrderItemBase,
    CreateProductOrder,
    UpdateProductOrder,
    UpdateProductOrderStatus,
    InventoryAdjustment,
    OrderInventoryUpdate,
    # Reservation
    ReservationSettings,
    CreateReservationSettings,
    UpdateReservationSettings,
    Reservation,
    CreateReservation,
    UpdateReservation,
    # Reservation resource
    Resource,
    CreateResource,
    UpdateResource,
    RoomResource,
    RentalResource,
    # Service appointment
    ServiceAppointment,
    CreateServiceAppointment,
    UpdateServiceAppointment,
    # Service configuration
    BusinessServiceConfig,
    CreateBusinessService,
    UpdateBusinessService,
    ServiceQRCode,
    # Service person
    ServicePerson,
    CreateServicePerson,
    UpdateServicePerson,
    # Property configuration
    Property,
    CreateProperty,
    UpdateProperty,
    PropertyCategory,
    CreatePropertyCategory,
    UpdatePropertyCategory,
    PropertyAddress,
    CreatePropertyAddress,
    UpdatePropertyAddress,
    PropertyFeatures,
    PropertyCatalog,
    BusinessPropertyCatalog,
    Coordinates,
    # Property inquiry
    PropertyInquiry,
    CreatePropertyInquiry,
    UpdatePropertyInquiry,
    UpdatePropertyInquiryStatus,
)

# Conversation models
from wiil.models.conversation import (
    # Conversation configuration
    BaseConversationConfig,
    CallTransfer,
    ConversationFilters,
    ConversationQueryOptions,
    ConversationSorting,
    ConversationStateHistory,
    ConversationSummary,
    DateRange,
    DecommissionConfig,
    Message,
    ServiceConversationConfig,
    # Conversation messages
    AssistantChatMessage,
    AssistantEmailMessage,
    BaseChatMessage,
    BaseEmailMessage,
    ChatMessage,
    ConversationMessage,
    UserChatMessage,
    UserEmailMessage,
    # Translation config
    CreateTranslationServiceRequest,
    TranslationConversationConfig,
    TranslationServiceRequest,
    # Translation conversation
    CreateTranslationParticipant,
    CreateTranslationServiceLog,
    TranslationMessage,
    TranslationParticipant,
    TranslationServiceLog,
    UpdateTranslationParticipant,
    UpdateTranslationServiceLog,
)

# Request models
from wiil.models.request import (
    AccountPaginatedTimestampQuery,
    BasePaginatedResult,
    PaginatedAccountRequest,
    PaginatedResultType,
    PaginationMeta,
    PaginationRequest,
    SearchablePaginationRequest,
    SortDirection,
    TimestampQuery,
)

# Service configuration models
from wiil.models.service_mgt import (
    # Agent configuration
    AgentConfiguration,
    AgentConfigurationDeleteRequest,
    CreateAgentConfiguration,
    UpdateAgentConfiguration,
    # Call transfer
    CallTransferConfig,
    TransferType,
    # Deployment configuration
    CreateChainDeploymentConfiguration,
    CreateDeploymentConfiguration,
    DeploymentConfiguration,
    DeploymentConfigurationDetails,
    DeploymentConfigurationResult,
    UpdateDeploymentConfiguration,
    # Instruction configuration
    CreateInstructionConfiguration,
    InstructionConfiguration,
    UpdateInstructionConfiguration,
    # Interaction channels
    CallChannel,
    ChannelConfiguration,
    ChannelSetupRequest,
    ChannelUpdateRequest,
    CreateDeploymentChannel,
    CreateMobileAppChannel,
    CreateWebChannel,
    DeploymentChannel,
    DeploymentChannelDeletionRequest,
    DeploymentChannelInfo,
    DeploymentChannelRequest,
    DeploymentChannelWithDeployment,
    MobileAppChannel,
    MobileAppChannelConfig,
    PhoneChannelConfig,
    SmsChannel,
    UpdateDeploymentChannel,
    WebChannel,
    WebChannelConfig,
    # Knowledge
    KnowledgeSource,
    # Phone configuration
    PhoneConfiguration,
    UpdatePhoneConfiguration,
    # Phone number
    BasePhoneNumberInfo,
    BusinessPhoneNumberPurchaseRequest,
    CreatePhoneNumberPurchase,
    PhoneCapabilities,
    PhoneNumberPrice,
    PhoneNumberPricing,
    PhoneNumberPurchase,
    PhoneProviderResponse,
    # Provisioning
    ChainConfiguration,
    CreateChainConfiguration,
    CreateProvisioningConfig,
    CreateTranslationChainConfig,
    ProvisioningConfigChain,
    SttModelConfig,
    TranslationChainConfig,
    TtsModelConfig,
    UpdateChainConfiguration,
    UpdateProvisioningConfig,
    UpdateTranslationChainConfig,
    # Support LLM
    WiilSupportModel,
    # Voice and language
    Language,
    SupportedLanguages,
    SupportedVoices,
    Voice,
    VoiceGender,
    # Dynamic setup
    DynamicAgentProcessingState,
    DynamicAgentSetupResult,
    DynamicBaseAgentSetup,
    DynamicModelConfiguration,
    DynamicPhoneAgentSetup,
    DynamicPhoneAgentSetupResult,
    DynamicSTTModelConfiguration,
    DynamicTTSModelConfiguration,
    DynamicWebAgentSetup,
    DynamicWebAgentSetupResult,
    ProcessingStatus,
    UpdateDynamicPhoneAgent,
    UpdateDynamicWebAgent,
)

# Re-export types for convenience
from wiil.types import (
    # Account types
    BusinessSupportServices,
    ServiceStatus,
    ServiceSuspensionType,
    # Business types
    AppointmentStatus,
    BestTimeToCall,
    BusinessDocumentTypes,
    BusinessServiceDocumentTypes,
    BusinessServiceType,
    CalendarProvider,
    CallPriority,
    InventoryUnit,
    MenuOrderType,
    OrderStatus,
    PaymentStatus,
    PreferredContactMethod,
    ProductOrderType,
    RecurrenceType,
    ReservationSettingType,
    ReservationSlotStatus,
    ResourceReservationDurationUnit,
    ResourceType,
    RestockStatus,
    StockAdjustmentType,
    StockStatus,
    # Service configuration types
    AssistantType,
    DeploymentProvisioningType,
    DeploymentStatus,
    DeploymentType,
    LLMRequestType,
    LLMType,
    MobilePlatform,
    ModelProprietor,
    OttCommunicationType,
    PhoneNumberType,
    PhonePurchaseStatus,
    PhoneStatus,
    ProviderType,
    SupportedLLMKit,
    SupportedProprietor,
    # Conversation types
    ConversationDirection,
    ConversationEventType,
    ConversationStatus,
    ConversationSummarySentiment,
    MessageType,
    ServiceConversationType,
    TranslationDirection,
    # Knowledge types
    KnowledgeBaseProcessingStatus,
    KnowledgeTypes,
    StorageTier,
    SupportedDocumentTypes,
)

__all__ = [
    # Base models
    "Address",
    "BaseModel",
    "LanguageCode",
    # Account models
    "CreateProject",
    "Organization",
    "OrganizationServiceStatusRecord",
    "Project",
    "UpdateProject",
    "SUPPORTED_BUSINESS_VERTICALS",
    "SupportedBusinessVerticalId",
    # Assistant setup models
    "AssistantSetupResult",
    "AdvanceBaseAssistant",
    "BaseAssistant",
    "ChainedPhoneAssistantSetup",
    "ChainedWebAssistantSetup",
    "PhoneAssistantSetup",
    "WebAssistantSetup",
    # Business management models
    "AppointmentAdditionalInfo",
    "CreateAppointmentAdditionalInfo",
    "UpdateAppointmentAdditionalInfo",
    "AppointmentFieldConfig",
    "CreateAppointmentFieldConfig",
    "UpdateAppointmentFieldConfig",
    "Customer",
    "CreateCustomer",
    "UpdateCustomer",
    "MenuCategory",
    "CreateMenuCategory",
    "UpdateMenuCategory",
    "BusinessMenuItem",
    "CreateBusinessMenuItem",
    "UpdateBusinessMenuItem",
    "MenuQRCode",
    "NutritionalInfo",
    "MenuOrder",
    "MenuOrderItem",
    "MenuOrderItemBase",
    "MenuItemCustomization",
    "DeliveryAddress",
    "CreateMenuOrder",
    "UpdateMenuOrder",
    "UpdateMenuOrderStatus",
    "OrderAddress",
    "OrderCustomer",
    "OrderPricing",
    "ProductCategory",
    "CreateProductCategory",
    "UpdateProductCategory",
    "BusinessProduct",
    "CreateBusinessProduct",
    "UpdateBusinessProduct",
    "ProductDimensions",
    "ProductOrder",
    "ProductOrderItem",
    "ProductOrderItemBase",
    "CreateProductOrder",
    "UpdateProductOrder",
    "UpdateProductOrderStatus",
    "InventoryAdjustment",
    "OrderInventoryUpdate",
    "ReservationSettings",
    "CreateReservationSettings",
    "UpdateReservationSettings",
    "Reservation",
    "CreateReservation",
    "UpdateReservation",
    "Resource",
    "CreateResource",
    "UpdateResource",
    "RoomResource",
    "RentalResource",
    "ServiceAppointment",
    "CreateServiceAppointment",
    "UpdateServiceAppointment",
    "BusinessServiceConfig",
    "CreateBusinessService",
    "UpdateBusinessService",
    "ServiceQRCode",
    "ServicePerson",
    "CreateServicePerson",
    "UpdateServicePerson",
    "Property",
    "CreateProperty",
    "UpdateProperty",
    "PropertyCategory",
    "CreatePropertyCategory",
    "UpdatePropertyCategory",
    "PropertyAddress",
    "CreatePropertyAddress",
    "UpdatePropertyAddress",
    "PropertyFeatures",
    "PropertyCatalog",
    "BusinessPropertyCatalog",
    "Coordinates",
    "PropertyInquiry",
    "CreatePropertyInquiry",
    "UpdatePropertyInquiry",
    "UpdatePropertyInquiryStatus",
    # Conversation models
    "BaseConversationConfig",
    "CallTransfer",
    "ConversationFilters",
    "ConversationQueryOptions",
    "ConversationSorting",
    "ConversationStateHistory",
    "ConversationSummary",
    "DateRange",
    "DecommissionConfig",
    "Message",
    "ServiceConversationConfig",
    "AssistantChatMessage",
    "AssistantEmailMessage",
    "BaseChatMessage",
    "BaseEmailMessage",
    "ChatMessage",
    "ConversationMessage",
    "UserChatMessage",
    "UserEmailMessage",
    "CreateTranslationServiceRequest",
    "TranslationConversationConfig",
    "TranslationServiceRequest",
    "CreateTranslationParticipant",
    "CreateTranslationServiceLog",
    "TranslationMessage",
    "TranslationParticipant",
    "TranslationServiceLog",
    "UpdateTranslationParticipant",
    "UpdateTranslationServiceLog",
    # Request models
    "AccountPaginatedTimestampQuery",
    "BasePaginatedResult",
    "PaginatedAccountRequest",
    "PaginatedResultType",
    "PaginationMeta",
    "PaginationRequest",
    "SearchablePaginationRequest",
    "SortDirection",
    "TimestampQuery",
    # Service configuration models
    "AgentConfiguration",
    "AgentConfigurationDeleteRequest",
    "CreateAgentConfiguration",
    "UpdateAgentConfiguration",
    "CallTransferConfig",
    "TransferType",
    "CreateChainDeploymentConfiguration",
    "CreateDeploymentConfiguration",
    "DeploymentConfiguration",
    "DeploymentConfigurationDetails",
    "DeploymentConfigurationResult",
    "UpdateDeploymentConfiguration",
    "CreateInstructionConfiguration",
    "InstructionConfiguration",
    "UpdateInstructionConfiguration",
    "CallChannel",
    "ChannelConfiguration",
    "ChannelSetupRequest",
    "ChannelUpdateRequest",
    "CreateDeploymentChannel",
    "CreateMobileAppChannel",
    "CreateWebChannel",
    "DeploymentChannel",
    "DeploymentChannelDeletionRequest",
    "DeploymentChannelInfo",
    "DeploymentChannelRequest",
    "DeploymentChannelWithDeployment",
    "MobileAppChannel",
    "MobileAppChannelConfig",
    "PhoneChannelConfig",
    "SmsChannel",
    "UpdateDeploymentChannel",
    "WebChannel",
    "WebChannelConfig",
    "KnowledgeSource",
    "PhoneConfiguration",
    "UpdatePhoneConfiguration",
    "BasePhoneNumberInfo",
    "BusinessPhoneNumberPurchaseRequest",
    "CreatePhoneNumberPurchase",
    "PhoneCapabilities",
    "PhoneNumberPrice",
    "PhoneNumberPricing",
    "PhoneNumberPurchase",
    "PhoneProviderResponse",
    "ChainConfiguration",
    "CreateChainConfiguration",
    "CreateProvisioningConfig",
    "CreateTranslationChainConfig",
    "ProvisioningConfigChain",
    "SttModelConfig",
    "TranslationChainConfig",
    "TtsModelConfig",
    "UpdateChainConfiguration",
    "UpdateProvisioningConfig",
    "UpdateTranslationChainConfig",
    "WiilSupportModel",
    "Language",
    "SupportedLanguages",
    "SupportedVoices",
    "Voice",
    "VoiceGender",
    "DynamicAgentProcessingState",
    "DynamicAgentSetupResult",
    "DynamicBaseAgentSetup",
    "DynamicModelConfiguration",
    "DynamicPhoneAgentSetup",
    "DynamicPhoneAgentSetupResult",
    "DynamicSTTModelConfiguration",
    "DynamicTTSModelConfiguration",
    "DynamicWebAgentSetup",
    "DynamicWebAgentSetupResult",
    "ProcessingStatus",
    "UpdateDynamicPhoneAgent",
    "UpdateDynamicWebAgent",
    # Account types
    "BusinessSupportServices",
    "ServiceStatus",
    "ServiceSuspensionType",
    # Business types
    "AppointmentStatus",
    "BestTimeToCall",
    "BusinessDocumentTypes",
    "BusinessServiceDocumentTypes",
    "BusinessServiceType",
    "CalendarProvider",
    "CallPriority",
    "InventoryUnit",
    "MenuOrderType",
    "OrderStatus",
    "PaymentStatus",
    "PreferredContactMethod",
    "ProductOrderType",
    "RecurrenceType",
    "ReservationSettingType",
    "ReservationSlotStatus",
    "ResourceReservationDurationUnit",
    "ResourceType",
    "RestockStatus",
    "StockAdjustmentType",
    "StockStatus",
    # Service configuration types
    "AssistantType",
    "DeploymentProvisioningType",
    "DeploymentStatus",
    "DeploymentType",
    "LLMRequestType",
    "LLMType",
    "MobilePlatform",
    "ModelProprietor",
    "OttCommunicationType",
    "PhoneNumberType",
    "PhonePurchaseStatus",
    "PhoneStatus",
    "ProviderType",
    "SupportedLLMKit",
    "SupportedProprietor",
    # Conversation types
    "ConversationDirection",
    "ConversationEventType",
    "ConversationStatus",
    "ConversationSummarySentiment",
    "MessageType",
    "ServiceConversationType",
    "TranslationDirection",
    # Knowledge types
    "KnowledgeBaseProcessingStatus",
    "KnowledgeTypes",
    "StorageTier",
    "SupportedDocumentTypes",
]
