"""Pydantic models for WIIL Platform entities."""

# Base models
from wiil.models.base import Address, BaseModel, LanguageCode

# Account models
from wiil.models.account import (
    CreateProject,
    Organization,
    OrganizationServiceStatusRecord,
    Project,
    UpdateProject,
)

# Service Management models
from wiil.models.service_mgt import (
    AgentConfiguration,
    CallTransferConfig,
    CreateAgentConfiguration,
    CreateInstructionConfiguration,
    InstructionConfiguration,
    Language,
    TransferType,
    WiilSupportModel,
    UpdateAgentConfiguration,
    UpdateInstructionConfiguration,
    Voice,
    VoiceGender,
)

# Re-export types for convenience
from wiil.types import (
    # Account types
    BusinessSupportServices,
    ServiceStatus,
    ServiceSuspensionType,
    # Business types
    AppointmentStatus,
    BestTimeToCall,
    BusinessDocumentTypes,
    BusinessServiceDocumentTypes,
    BusinessServiceType,
    CalendarProvider,
    CallPriority,
    InventoryUnit,
    MenuOrderType,
    OrderStatus,
    PaymentStatus,
    PreferredContactMethod,
    ProductOrderType,
    RecurrenceType,
    ReservationSettingType,
    ReservationSlotStatus,
    ResourceReservationDurationUnit,
    ResourceType,
    RestockStatus,
    StockAdjustmentType,
    StockStatus,
    # Service types
    AssistantType,
    DeploymentProvisioningType,
    DeploymentStatus,
    DeploymentType,
    LLMRequestType,
    LLMType,
    MobilePlatform,
    ModelProprietor,
    OttCommunicationType,
    PhoneNumberType,
    PhonePurchaseStatus,
    PhoneStatus,
    ProviderType,
    SupportedLLMKit,
    SupportedProprietor,
    # Conversation types
    ConversationEventType,
    ConversationStatus,
    ConversationSummarySentiment,
    ServiceConversationType,
    TranslationDirection,
    # Knowledge types
    KnowledgeBaseProcessingStatus,
    KnowledgeTypes,
    StorageTier,
    SupportedDocumentTypes,
)

__all__ = [
    # Base models
    "Address",
    "BaseModel",
    "LanguageCode",
    # Account models
    "CreateProject",
    "Organization",
    "OrganizationServiceStatusRecord",
    "Project",
    "UpdateProject",
    # Service Management models
    "AgentConfiguration",
    "CallTransferConfig",
    "CreateAgentConfiguration",
    "CreateInstructionConfiguration",
    "InstructionConfiguration",
    "Language",
    "TransferType",
    "WiilSupportModel",
    "UpdateAgentConfiguration",
    "UpdateInstructionConfiguration",
    "Voice",
    "VoiceGender",
    # Account types
    "BusinessSupportServices",
    "ServiceStatus",
    "ServiceSuspensionType",
    # Business types
    "AppointmentStatus",
    "BestTimeToCall",
    "BusinessDocumentTypes",
    "BusinessServiceDocumentTypes",
    "BusinessServiceType",
    "CalendarProvider",
    "CallPriority",
    "InventoryUnit",
    "MenuOrderType",
    "OrderStatus",
    "PaymentStatus",
    "PreferredContactMethod",
    "ProductOrderType",
    "RecurrenceType",
    "ReservationSettingType",
    "ReservationSlotStatus",
    "ResourceReservationDurationUnit",
    "ResourceType",
    "RestockStatus",
    "StockAdjustmentType",
    "StockStatus",
    # Service types
    "AssistantType",
    "DeploymentProvisioningType",
    "DeploymentStatus",
    "DeploymentType",
    "LLMRequestType",
    "LLMType",
    "MobilePlatform",
    "ModelProprietor",
    "OttCommunicationType",
    "PhoneNumberType",
    "PhonePurchaseStatus",
    "PhoneStatus",
    "ProviderType",
    "SupportedLLMKit",
    "SupportedProprietor",
    # Conversation types
    "ConversationEventType",
    "ConversationStatus",
    "ConversationSummarySentiment",
    "ServiceConversationType",
    "TranslationDirection",
    # Knowledge types
    "KnowledgeBaseProcessingStatus",
    "KnowledgeTypes",
    "StorageTier",
    "SupportedDocumentTypes",
]
