"""Business management resource classes for business operations."""

from .customer_management import (
    CustomerGroupsResource,
    CustomersResource,
    ShippingAddressesResource,
)
from .menu_management import (
    MenuItemVariantsResource,
    MenuOrdersResource,
    MenuPricingRulesResource,
    MenusResource,
    MenuSetsResource,
    ModifiersResource,
)
from .product_management import (
    ProductAxisBindingsResource,
    ProductOrdersResource,
    ProductPricingRulesResource,
    ProductsResource,
    ProductSetsResource,
    ProductVariantAxesResource,
    ProductVariantsResource,
)
from .pricing_rules import DiscountRulesResource, TaxRulesResource
from .location_management import BusinessLocationsResource
from .property_management import (
    PropertyConfigResource,
    PropertyInquiryResource,
)
from .reservation_management import (
    FloorPlansResource,
    FloorPlanSectionsResource,
    MaintenanceBlocksResource,
    RentalAssignmentsResource,
    RentalReservationsResource,
    ReservationResourcesResource,
    ReservationSettingsResource,
    ResourceCategoriesResource,
    ResourceInstancesResource,
    RoomAssignmentsResource,
    RoomReservationsResource,
    TableAssignmentsResource,
    TableReservationsResource,
)
from .service_management import (
    AppointmentAdditionalInfoResource,
    AppointmentFieldConfigsResource,
    BusinessServicesResource,
    ServiceAppointmentsResource,
    ServiceCategoriesResource,
    ServicePersonsResource,
    ServicePricingRulesResource,
    ServiceProvidersResource,
    ServiceTimeOffsResource,
)

__all__ = [
    'CustomersResource',
    'CustomerGroupsResource',
    'ShippingAddressesResource',
    'MenusResource',
    'MenuOrdersResource',
    'MenuItemVariantsResource',
    'MenuPricingRulesResource',
    'MenuSetsResource',
    'ModifiersResource',
    'ProductsResource',
    'ProductOrdersResource',
    'ProductVariantsResource',
    'ProductVariantAxesResource',
    'ProductAxisBindingsResource',
    'ProductSetsResource',
    'ProductPricingRulesResource',
    'DiscountRulesResource',
    'TaxRulesResource',
    'ReservationResourcesResource',
    'ReservationSettingsResource',
    'ResourceCategoriesResource',
    'ResourceInstancesResource',
    'FloorPlansResource',
    'FloorPlanSectionsResource',
    'MaintenanceBlocksResource',
    'TableAssignmentsResource',
    'RoomAssignmentsResource',
    'RentalAssignmentsResource',
    'TableReservationsResource',
    'RoomReservationsResource',
    'RentalReservationsResource',
    'AppointmentAdditionalInfoResource',
    'AppointmentFieldConfigsResource',
    'ServiceAppointmentsResource',
    'BusinessServicesResource',
    'ServiceCategoriesResource',
    'ServicePersonsResource',
    'ServicePricingRulesResource',
    'ServiceProvidersResource',
    'ServiceTimeOffsResource',
    'PropertyConfigResource',
    'PropertyInquiryResource',
    'BusinessLocationsResource',
]
